import {
  RECOMMENDATION_CLUSTERS,
  RecommendationCluster,
  STORE_AREAS,
  STORE_REGIONS,
} from '@/lib/types';

const AREA_CLUSTER_ENTRIES: Array<readonly [string, RecommendationCluster]> = [
  [STORE_AREAS.CENTRAL_WESTERN, RECOMMENDATION_CLUSTERS.HK_ISLAND_WEST],
  [STORE_AREAS.WAN_CHAI, RECOMMENDATION_CLUSTERS.HK_ISLAND_WEST],
  [STORE_AREAS.SOUTHERN, RECOMMENDATION_CLUSTERS.HK_ISLAND_WEST],
  [STORE_AREAS.EASTERN, RECOMMENDATION_CLUSTERS.HK_ISLAND_EAST],
  [STORE_AREAS.YAU_TSIM_MONG, RECOMMENDATION_CLUSTERS.WEST_KOWLOON],
  [STORE_AREAS.SHAM_SHUI_PO, RECOMMENDATION_CLUSTERS.WEST_KOWLOON],
  [STORE_AREAS.KOWLOON_CITY, RECOMMENDATION_CLUSTERS.WEST_KOWLOON],
  [STORE_AREAS.WONG_TAI_SIN, RECOMMENDATION_CLUSTERS.EAST_KOWLOON],
  [STORE_AREAS.KWUN_TONG, RECOMMENDATION_CLUSTERS.EAST_KOWLOON],
  [STORE_AREAS.SHA_TIN, RECOMMENDATION_CLUSTERS.SHA_TIN_BELT],
  [STORE_AREAS.TAI_PO, RECOMMENDATION_CLUSTERS.NORTH_NT],
  [STORE_AREAS.NORTH, RECOMMENDATION_CLUSTERS.NORTH_NT],
  [STORE_AREAS.SAI_KUNG, RECOMMENDATION_CLUSTERS.TSEUNG_KWAN_O],
  [STORE_AREAS.KWAI_TSING, RECOMMENDATION_CLUSTERS.TSUEN_KWAN_WEST],
  [STORE_AREAS.TSUEN_WAN, RECOMMENDATION_CLUSTERS.TSUEN_KWAN_WEST],
  [STORE_AREAS.TUEN_MUN, RECOMMENDATION_CLUSTERS.FAR_WEST_NT],
  [STORE_AREAS.YUEN_LONG, RECOMMENDATION_CLUSTERS.FAR_WEST_NT],
];

const AREA_TO_CLUSTER = new Map<string, RecommendationCluster>(
  AREA_CLUSTER_ENTRIES.map(([area, cluster]) => [
    normalizeLocationValue(area),
    cluster,
  ])
);

const AREA_ALIAS_ENTRIES: Array<readonly [string, RecommendationCluster]> = [
  ['CENTRAL AND WESTERN', RECOMMENDATION_CLUSTERS.HK_ISLAND_WEST],
  ['WAN CHAI', RECOMMENDATION_CLUSTERS.HK_ISLAND_WEST],
  ['SOUTHERN', RECOMMENDATION_CLUSTERS.HK_ISLAND_WEST],
  ['EASTERN', RECOMMENDATION_CLUSTERS.HK_ISLAND_EAST],
  ['YAU TSIM MONG', RECOMMENDATION_CLUSTERS.WEST_KOWLOON],
  ['SHAM SHUI PO', RECOMMENDATION_CLUSTERS.WEST_KOWLOON],
  ['KOWLOON CITY', RECOMMENDATION_CLUSTERS.WEST_KOWLOON],
  ['WONG TAI SIN', RECOMMENDATION_CLUSTERS.EAST_KOWLOON],
  ['KWUN TONG', RECOMMENDATION_CLUSTERS.EAST_KOWLOON],
  ['TSEUNG KWAN O', RECOMMENDATION_CLUSTERS.TSEUNG_KWAN_O],
  ['將軍澳', RECOMMENDATION_CLUSTERS.TSEUNG_KWAN_O],
  ['TSEUNG KWAN O AREA', RECOMMENDATION_CLUSTERS.TSEUNG_KWAN_O],
  ['SHA TIN', RECOMMENDATION_CLUSTERS.SHA_TIN_BELT],
  ['TAI PO', RECOMMENDATION_CLUSTERS.NORTH_NT],
  ['NORTH', RECOMMENDATION_CLUSTERS.NORTH_NT],
  ['TSUEN WAN', RECOMMENDATION_CLUSTERS.TSUEN_KWAN_WEST],
  ['KWAI TSING', RECOMMENDATION_CLUSTERS.TSUEN_KWAN_WEST],
  ['TUEN MUN', RECOMMENDATION_CLUSTERS.FAR_WEST_NT],
  ['YUEN LONG', RECOMMENDATION_CLUSTERS.FAR_WEST_NT],
];

const AREA_ALIAS_TO_CLUSTER = new Map<string, RecommendationCluster>(
  AREA_ALIAS_ENTRIES.map(([area, cluster]) => [
    normalizeLocationValue(area),
    cluster,
  ])
);

const REGION_TO_CLUSTER = new Map<string, RecommendationCluster>([
  [
    normalizeLocationValue(STORE_REGIONS.HONG_KONG_ISLAND),
    RECOMMENDATION_CLUSTERS.HK_ISLAND_WEST,
  ],
]);

export const CLUSTER_ADJACENCY: Record<
  RecommendationCluster,
  RecommendationCluster[]
> = {
  HK_ISLAND_WEST: [
    RECOMMENDATION_CLUSTERS.WEST_KOWLOON,
    RECOMMENDATION_CLUSTERS.HK_ISLAND_EAST,
  ],
  HK_ISLAND_EAST: [
    RECOMMENDATION_CLUSTERS.HK_ISLAND_WEST,
    RECOMMENDATION_CLUSTERS.EAST_KOWLOON,
  ],
  WEST_KOWLOON: [
    RECOMMENDATION_CLUSTERS.HK_ISLAND_WEST,
    RECOMMENDATION_CLUSTERS.EAST_KOWLOON,
    RECOMMENDATION_CLUSTERS.TSUEN_KWAN_WEST,
  ],
  EAST_KOWLOON: [
    RECOMMENDATION_CLUSTERS.HK_ISLAND_EAST,
    RECOMMENDATION_CLUSTERS.WEST_KOWLOON,
    RECOMMENDATION_CLUSTERS.TSEUNG_KWAN_O,
    RECOMMENDATION_CLUSTERS.SHA_TIN_BELT,
  ],
  TSEUNG_KWAN_O: [
    RECOMMENDATION_CLUSTERS.EAST_KOWLOON,
    RECOMMENDATION_CLUSTERS.SHA_TIN_BELT,
  ],
  SHA_TIN_BELT: [
    RECOMMENDATION_CLUSTERS.EAST_KOWLOON,
    RECOMMENDATION_CLUSTERS.TSEUNG_KWAN_O,
    RECOMMENDATION_CLUSTERS.NORTH_NT,
    RECOMMENDATION_CLUSTERS.TSUEN_KWAN_WEST,
  ],
  NORTH_NT: [
    RECOMMENDATION_CLUSTERS.SHA_TIN_BELT,
    RECOMMENDATION_CLUSTERS.FAR_WEST_NT,
  ],
  TSUEN_KWAN_WEST: [
    RECOMMENDATION_CLUSTERS.WEST_KOWLOON,
    RECOMMENDATION_CLUSTERS.SHA_TIN_BELT,
    RECOMMENDATION_CLUSTERS.FAR_WEST_NT,
  ],
  FAR_WEST_NT: [
    RECOMMENDATION_CLUSTERS.TSUEN_KWAN_WEST,
    RECOMMENDATION_CLUSTERS.NORTH_NT,
  ],
  UNKNOWN: [],
};

function normalizeLocationValue(value: string): string {
  return value.trim().replace(/\s+/g, ' ').toUpperCase();
}

export function deriveRecommendationCluster(
  region: string,
  area: string
): RecommendationCluster {
  const normalizedArea = normalizeLocationValue(area);

  const mappedAreaCluster = AREA_TO_CLUSTER.get(normalizedArea);

  if (mappedAreaCluster) {
    return mappedAreaCluster;
  }

  const mappedAreaAliasCluster = AREA_ALIAS_TO_CLUSTER.get(normalizedArea);

  if (mappedAreaAliasCluster) {
    return mappedAreaAliasCluster;
  }

  const normalizedRegion = normalizeLocationValue(region);

  const mappedRegionCluster = REGION_TO_CLUSTER.get(normalizedRegion);

  if (mappedRegionCluster) {
    return mappedRegionCluster;
  }

  return RECOMMENDATION_CLUSTERS.UNKNOWN;
}
